name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Use the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version of setup-python
      with:
        python-version: '3.10'  # Update to the latest stable version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry

    - name: Download Asherah binaries
      run: |
        asherah/scripts/download-libasherah.sh

    - name: Package and publish with Poetry
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
