name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Use the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version of setup-python
      with:
        python-version: '3.11'  # Use the latest stable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Download Asherah binaries
      run: |
        asherah/scripts/download-libasherah.sh

    - name: Run tests
      run: |
        poetry run pytest --cov  # Run tests with coverage report
